### ISSUE TITLE
Add 93846-4 and 75928-2 to lab test query

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-monitoring#32]
Add 93846-4 and 75928-2 to lab test query

**Comment by KutSaleh** [comment]
@juliangruendner Is there anything new here? We need to add the two lab codes as soon as possible. Without these two codes, we are unable to deliver any responses, even though we have over 50 T resources available.
Please prioritize this task to ensure the system can respond as expected. Thank you for your prompt action!
